export const PROFILELIST = [
  {
    id: 1,
    name: "Maksudul Hasan",
    location: "Dhaka Bangladesh",
    join_time: "July 26th, 2022",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    profile_picture: "/static/profile1.jpg",
  },
  {
    id: 2,
    name: "Refez Hossain",
    location: "Dhaka Bangladesh",
    join_time: "July 26th, 2022",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    profile_picture: "/static/profile2.jpg",
  },
  {
    id: 3,
    name: "John Doe",
    location: "Dhaka Bangladesh",
    join_time: "July 26th, 2022",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    profile_picture: "/static/profile3.jpg",
  },
  {
    id: 4,
    name: "Neymar Jr.",
    location: "Dhaka Bangladesh",
    join_time: "July 26th, 2022",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    profile_picture: "/static/profile4.jpg",
  },
  {
    id: 5,
    name: "Jonathan Smith",
    location: "Dhaka Bangladesh",
    join_time: "July 26th, 2022",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    profile_picture: "/static/profile5.jpg",
  },
  {
    id: 6,
    name: "John Sina",
    location: "Dhaka Bangladesh",
    join_time: "July 26th, 2022",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    profile_picture: "/static/profile6.jpg",
  },
];
